//pic the values

const income = document.getElementById("income")
const incomeV = income.value

const food = document.getElementById("food")
const foodV = food.value

const Health = document.getElementById("Health")
const HealthV = Health.value

const fun = document.getElementById("fun")
const funV = fun.value

const couple = document.getElementById("couple")
const coupleV = couple.value

const family = document.getElementById("family")
const familyV = family.value

const services = document.getElementById("services")
const servicesV = services.value

const others = document.getElementById("others")
const othersV = others.value

           


            